"""Rebuild words_db.js from the supplied Anki package (Python standard library)."""
import html
import json
import re
import sqlite3
import tempfile
import unicodedata
import zipfile
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "data/JLPT_N5_to_N1_Japanese_Vocabulary.apkg"
READING_FIXES = {"ＯＫ": "オーケー", "ＯＵＴ": "アウト", "ＦＡＸ": "ファックス"}


def plain(value):
    return html.unescape(re.sub(r"<[^>]*>", "", value)).strip()


def kana(expression, reading):
    if expression in READING_FIXES:
        return READING_FIXES[expression]
    # Anki furigana: 食[た]べる → たべる; やり 遂[と]げる → やりとげる.
    result = re.sub(r"([^\s\[\]]+)\[([^\]]+)\]", lambda m: m[2], plain(reading))
    result = unicodedata.normalize("NFC", re.sub(r"\s+", "", result))
    if not re.fullmatch(r"[\u3041-\u3096\u30a1-\u30faー]+", result):
        raise ValueError(f"Invalid kana for {expression}: {result}")
    return result


def main():
    with zipfile.ZipFile(SOURCE) as package, tempfile.TemporaryDirectory() as temp:
        name = next(n for n in ("collection.anki21", "collection.anki2") if n in package.namelist())
        collection = Path(temp) / "collection.sqlite"
        collection.write_bytes(package.read(name))
        with sqlite3.connect(collection) as db:
            rows = db.execute("SELECT id, flds, tags FROM notes ORDER BY id").fetchall()
    levels = {str(level): [] for level in range(1, 6)}
    for note_id, fields, tags in rows:
        fields = fields.split("\x1f")
        jlpt = re.findall(r"\bjlpt_N([1-5])\b", tags)
        if len(jlpt) != 1 or len(fields) != 7:
            raise ValueError(f"Invalid source note {note_id}")
        expression, meaning, reading, grammar, extra, example, example_en = map(plain, fields)
        if not meaning:
            raise ValueError(f"Missing meaning for {note_id}")
        levels[str(6 - int(jlpt[0]))].append({
            "id": str(note_id), "jlpt": "N" + jlpt[0], "expression": expression,
            "reading": kana(expression, reading), "meaning": meaning,
            "grammar": grammar, "additionalMeaning": extra,
        })
    output = "// Generated by tools/import_vocab.py; levels 1–5 correspond to JLPT N5–N1.\n"
    output += "const WORDS_DB = " + json.dumps(levels, ensure_ascii=False, indent=2) + ";\n"
    (ROOT / "words_db.js").write_text(output, encoding="utf-8")
    print(json.dumps({f"N{6-int(k)}": len(v) for k, v in levels.items()}))


if __name__ == "__main__":
    main()
